"""feat: event 테이블 추가

Revision ID: dc7b8377acd5
Revises: 3e08a9570f0c
Create Date: 2026-09-17 16:51:33.323455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7b8377acd5'
down_revision = '3e08a9570f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='행사 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='행사명 (최대 200자)'),
    sa.Column('category', sa.Enum('FESTIVAL', 'EXHIBITION', 'PERFORMANCE', 'EXPERIENCE', 'SEASONAL'), nullable=False, comment='카테고리 (축제/전시/공연/체험/계절행사)'),
    sa.Column('region', sa.Enum('DONGNAM', 'SEOBUK'), nullable=False, comment='행정구역 구분 (동남구/서북구)'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='행사 시작일'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='행사 종료일 (당일 행사는 start_date와 동일'),
    sa.Column('start_time', sa.Time(), nullable=True, comment='시작 시각'),
    sa.Column('end_time', sa.Time(), nullable=True, comment='종료 시각'),
    sa.Column('location', sa.String(length=200), nullable=False, comment='장소명 (예: 천안시민체육공원)'),
    sa.Column('address', sa.String(length=300), nullable=True, comment='상세 도로명/지번 주소'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False, comment='위도 (Latitude)'),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False, comment='경도 (Longitude)'),
    sa.Column('price_type', sa.Enum('FREE', 'PAID'), nullable=False, comment='무료/유료 여부'),
    sa.Column('price_amount', sa.Integer(), nullable=True, comment='입장 요금(원)'),
    sa.Column('organizer', sa.String(length=200), nullable=True, comment='주최/주관 기관명'),
    sa.Column('contact', sa.String(length=100), nullable=True, comment='문의처 전화번호'),
    sa.Column('homepage_url', sa.String(length=500), nullable=True, comment='공식 홈페이지 링크 URL'),
    sa.Column('description', sa.Text(), nullable=True, comment='행사 상세 소개 본문'),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='대표 이미지/포스터 URL'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='데이터 등록 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
