"""review event FK 연결

Revision ID: fd8da9482b62
Revises: 79a5f022beaa
Create Date: 2026-10-04 15:53:08.797427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd8da9482b62'
down_revision = '79a5f022beaa'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('event_id', sa.Integer(), nullable=False)
        )

        batch_op.drop_index(
            batch_op.f('ix_review_tour_content_id')
        )

        batch_op.create_index(
            batch_op.f('ix_review_event_id'),
            ['event_id'],
            unique=False
        )

        batch_op.create_foreign_key(
            'fk_review_event_id',
            'events',
            ['event_id'],
            ['id']
        )

        batch_op.drop_column('tour_content_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_content_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(
            'fk_review_event_id',
            type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_review_event_id'))
        batch_op.create_index(batch_op.f('ix_review_tour_content_id'), ['tour_content_id'], unique=False)
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
